name: Publish Docker image

on:
  push:
    branches:
      - node-18.17.1-bullseye
  release:
    types: [published]
  workflow_dispatch:

env:
  DOCKER_NAME: "vincentking/node"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: get_image_name
        run: |
          VERSION=bullseye

          IMAGE_NAME=${{ env.DOCKER_NAME }}:$VERSION

          echo IMAGE_NAME=$IMAGE_NAME

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
          tags: ${{ env.IMAGE_NAME }}
